### ISSUE TITLE
HTML format in redcap, do we need it in schema or in CE patient showpage?

### ISSUE THREAD

**Issue by SenseCode** [utsw-bicf/cognitionexplorer#95]
- [ ] Get rid of the useless format part in ivp_d1, instruction and question No. 5

![image](https://user-images.githubusercontent.com/38848214/100666885-68c9f200-331f-11eb-8a01-0d3d87ed7df8.png)

![image](https://user-images.githubusercontent.com/38848214/100664820-ba717d00-331d-11eb-9928-6611e08e51c7.png)
![image](https://user-images.githubusercontent.com/38848214/100665390-d2e19780-331d-11eb-948b-13d1fe0b5956.png)

- [ ]  Make sure with entry database:  output are only numbers, no any format inside if the output data is text.
Example as ivp_c1:

![image](https://user-images.githubusercontent.com/38848214/100666129-218f3180-331e-11eb-89fc-9883cd81a641.png)

**Comment by jay-gates** [comment]
I think there are multiple issues here:
1. Some item (question) and response text is being used for UI purposes, to guide the user in answering the questions and understanding the branching logic. This is largely due to REDCap's form layout limitations and probably also mirrors the actual paper form layout.
2. Some item text has embedded <b> tags, which aren't needed (REDCap automatically bolds the item text); these should be removed.
3. Some response text has embedded formatting (`<b>, <i>`) which probably mirrors the paper forms; I would recommend stripping these tags from the raw REDCap data export programmatically, rather than limiting the REDCap instrument design to only use plain text.
4. Some item and response text has extra/unneeded non-breaking spaces (probably from copy/pasting) which should be removed from the REDCap forms, but I would recommend stripping these programmatically from data exports as well; also consider that there may be additional HTML entities present as well.

**Comment by SenseCode** [comment]
I stripped all the these HTML-related formats or tags in primary schemas so far, just wait to test and check if they fit with real data. Thanks for your reply.
